import type { Lead, OpportunityStage } from "./types"

export const carriers = ["Arden", "Acme Insurance", "Northwind"]
export const agents = ["Alex Carter", "Priya N.", "Diego R."]
export const communities = ["Retail", "Healthcare", "Construction"]
export const stages = ["Lead Created", "Submission Sent", "Quote Received", "Bound", "Policy Issued"]

export const detailedStages: OpportunityStage[] = [
  "Lead Intake",
  "Information Gathering",
  "Carrier Selection",
  "Form Completion",
  "Submission",
  "Quote/Bind",
  "Policy Issued",
]

export const leadsData: Lead[] = [
  {
    id: "c1",
    client_name: "Blue Harbor LLC",
    state: "CA",
    quote_or_inquiry: "quote",
    status: "form filling stage",
    assigned_underwriter: "Morgan Lee",
    needby_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    effective_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    last_updated: new Date().toISOString(),
    carrier: "Arden",
    agent: "Alex Carter",
    community: "Retail",
    stage: "Submission Sent",
    missing_items: ["Loss runs", "Acord 125"],
    opportunity_id: "OPP-2025-0001",
    detailed_stage: "Form Completion",
    client_email: "ops@blueharbor.example",
    client_phone: "(555) 201-1193",
    property: {
      address: "1200 Harbor Blvd, San Diego, CA",
      sq_ft: 54000,
      construction_type: "Masonry Non-Combustible",
      year_built: 2004,
    },
    coverage_requested: ["General Liability", "Property", "Umbrella"],
    missing_fields: ["Year Built"], // example highlight
    carrier_options: [
      {
        name: "Travelers",
        fit_score: 92,
        requirements: ["Acord 125", "Loss runs (5 yrs)"],
        reason: "Sprinkler system present, property value $2.5M, Dallas location",
        selected: true,
      },
      {
        name: "Arden",
        fit_score: 88,
        requirements: ["Acord 125", "Acord 140", "SOV"],
        reason: "Good fit for retail footprint and updated roof",
      },
      { name: "Northwind", fit_score: 73, requirements: ["Acord 125"], reason: "Basic eligibility met" },
    ],
    forms: [
      { id: "f-125", name: "Acord 125", status: "ai-filled", ai_confidence: 86, download_url: "#" },
      { id: "f-140", name: "Acord 140", status: "pending", ai_confidence: 0 },
      { id: "f-loss", name: "Loss Runs (5 yrs)", status: "uploaded" },
    ],
    supporting_docs: [
      { id: "d-photos", name: "Photos", uploaded: true },
      { id: "d-inspection", name: "Inspection Report", uploaded: false },
    ],
    submission: { status: "pending" },
    quotes: [
      {
        carrier: "Travelers",
        premium: 12500,
        deductible: 1000,
        effective_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
        selected: true,
      },
    ],
    policy: undefined,
  },
  {
    id: "c2",
    client_name: "Silver Pine Inc",
    state: "TX",
    quote_or_inquiry: "inquiry",
    status: "submitted",
    assigned_underwriter: "Jamie Park",
    needby_date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    effective_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    last_updated: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    carrier: "Acme Insurance",
    agent: "Priya N.",
    community: "Healthcare",
    stage: "Lead Created",
    opportunity_id: "OPP-2025-0002",
    detailed_stage: "Lead Intake",
    client_email: "ops@silverpine.example",
    client_phone: "(555) 201-1194",
    property: {
      address: "1400 Pine St, Dallas, TX",
      sq_ft: 30000,
      construction_type: "Wood Frame",
      year_built: 1990,
    },
    coverage_requested: ["General Liability"],
    missing_fields: [],
    carrier_options: [
      {
        name: "Travelers",
        fit_score: 85,
        requirements: ["Acord 125"],
        reason: "Basic eligibility met",
        selected: false,
      },
      {
        name: "Arden",
        fit_score: 80,
        requirements: ["Acord 125"],
        reason: "Basic eligibility met",
      },
      { name: "Northwind", fit_score: 75, requirements: ["Acord 125"], reason: "Basic eligibility met" },
    ],
    forms: [
      { id: "f-125", name: "Acord 125", status: "pending", ai_confidence: 0, download_url: "#" },
      { id: "f-140", name: "Acord 140", status: "pending", ai_confidence: 0 },
      { id: "f-loss", name: "Loss Runs (5 yrs)", status: "pending" },
    ],
    supporting_docs: [
      { id: "d-photos", name: "Photos", uploaded: false },
      { id: "d-inspection", name: "Inspection Report", uploaded: false },
    ],
    submission: { status: "pending" },
    quotes: [],
    policy: undefined,
  },
  {
    id: "c3",
    client_name: "Cobalt Works",
    state: "FL",
    quote_or_inquiry: "quote",
    status: "submitted quote",
    assigned_underwriter: "Riley Chen",
    needby_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    effective_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    last_updated: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    carrier: "Northwind",
    agent: "Diego R.",
    community: "Construction",
    stage: "Quote Received",
    opportunity_id: "OPP-2025-0003",
    detailed_stage: "Quote/Bind",
    client_email: "ops@cobaltworks.example",
    client_phone: "(555) 201-1195",
    property: {
      address: "1600 Works St, Miami, FL",
      sq_ft: 70000,
      construction_type: "Steel Frame",
      year_built: 1985,
    },
    coverage_requested: ["General Liability", "Property"],
    missing_fields: [],
    carrier_options: [
      {
        name: "Travelers",
        fit_score: 82,
        requirements: ["Acord 125", "Loss runs (5 yrs)"],
        reason: "Sprinkler system present, property value $3.5M, Miami location",
        selected: false,
      },
      {
        name: "Arden",
        fit_score: 78,
        requirements: ["Acord 125", "Acord 140", "SOV"],
        reason: "Good fit for construction footprint",
      },
      { name: "Northwind", fit_score: 70, requirements: ["Acord 125"], reason: "Basic eligibility met" },
    ],
    forms: [
      { id: "f-125", name: "Acord 125", status: "uploaded", ai_confidence: 100, download_url: "#" },
      { id: "f-140", name: "Acord 140", status: "pending", ai_confidence: 0 },
      { id: "f-loss", name: "Loss Runs (5 yrs)", status: "uploaded" },
    ],
    supporting_docs: [
      { id: "d-photos", name: "Photos", uploaded: true },
      { id: "d-inspection", name: "Inspection Report", uploaded: true },
    ],
    submission: { status: "pending" },
    quotes: [
      {
        carrier: "Arden",
        premium: 15000,
        deductible: 2000,
        effective_date: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
        selected: true,
      },
    ],
    policy: undefined,
  },
  {
    id: "c4",
    client_name: "Harbor Bistro",
    state: "NY",
    quote_or_inquiry: "quote",
    status: "submitted but requires additional info",
    assigned_underwriter: "Morgan Lee",
    needby_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    effective_date: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    last_updated: new Date().toISOString(),
    carrier: "Arden",
    agent: "Alex Carter",
    community: "Retail",
    stage: "Lead Created",
    opportunity_id: "OPP-2025-0004",
    detailed_stage: "Lead Intake",
    client_email: "hello@harborbistro.example",
    client_phone: "(555) 201-1196",
    property: { address: "22 Pier Ave, NYC, NY", sq_ft: 12000, construction_type: "Masonry", year_built: 1998 },
    coverage_requested: ["General Liability"],
    missing_fields: ["Number of employees"],
    carrier_options: [],
    forms: [
      { id: "f-125", name: "Acord 125", status: "pending", ai_confidence: 0 },
      { id: "f-140", name: "Acord 140", status: "pending", ai_confidence: 0 },
    ],
    supporting_docs: [{ id: "d-menu", name: "Menu PDF", uploaded: false }],
    submission: { status: "pending" },
    quotes: [],
    policy: undefined,
  },
  {
    id: "c5",
    client_name: "MedCore Labs",
    state: "MA",
    quote_or_inquiry: "quote",
    status: "form filling stage",
    assigned_underwriter: "Jamie Park",
    needby_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    effective_date: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    last_updated: new Date().toISOString(),
    carrier: "Acme Insurance",
    agent: "Priya N.",
    community: "Healthcare",
    stage: "Submission Sent",
    opportunity_id: "OPP-2025-0005",
    detailed_stage: "Information Gathering",
    client_email: "ops@medcore.example",
    client_phone: "(555) 201-1197",
    property: { address: "18 Research Way, Boston, MA", sq_ft: 45000, construction_type: "Steel", year_built: 2012 },
    coverage_requested: ["Property", "General Liability"],
    missing_fields: ["Alarm cert"],
    carrier_options: [
      { name: "Arden", fit_score: 84, requirements: ["Acord 125"], reason: "Healthcare specialization" },
      { name: "Northwind", fit_score: 72, requirements: ["Acord 125"], reason: "Basic eligibility" },
    ],
    forms: [
      { id: "f-125", name: "Acord 125", status: "ai-filled", ai_confidence: 81 },
      { id: "f-140", name: "Acord 140", status: "pending", ai_confidence: 0 },
    ],
    supporting_docs: [{ id: "d-cert", name: "UL Alarm Certificate", uploaded: false }],
    submission: { status: "pending" },
    quotes: [],
    policy: undefined,
  },
  {
    id: "c6",
    client_name: "Everbuild Co.",
    state: "IL",
    quote_or_inquiry: "quote",
    status: "submitted quote",
    assigned_underwriter: "Riley Chen",
    needby_date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    effective_date: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
    last_updated: new Date().toISOString(),
    carrier: "Northwind",
    agent: "Diego R.",
    community: "Construction",
    stage: "Quote Received",
    opportunity_id: "OPP-2025-0006",
    detailed_stage: "Carrier Selection",
    client_email: "ops@everbuild.example",
    client_phone: "(555) 201-1198",
    property: { address: "600 Lakeview Dr, Chicago, IL", sq_ft: 82000, construction_type: "Steel", year_built: 2001 },
    coverage_requested: ["General Liability", "Umbrella"],
    missing_fields: [],
    carrier_options: [
      { name: "Arden", fit_score: 79, requirements: ["Acord 125", "SOV"], reason: "Good claims history" },
      { name: "Travelers", fit_score: 83, requirements: ["Acord 125"], reason: "Strong eligibility" },
    ],
    forms: [
      { id: "f-125", name: "Acord 125", status: "uploaded", ai_confidence: 100 },
      { id: "f-loss", name: "Loss Runs (5 yrs)", status: "uploaded" },
    ],
    supporting_docs: [{ id: "d-photos", name: "Photos", uploaded: true }],
    submission: { status: "pending" },
    quotes: [
      {
        carrier: "Travelers",
        premium: 18900,
        deductible: 2500,
        effective_date: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
        selected: false,
      },
    ],
    policy: undefined,
  },
  {
    id: "c7",
    client_name: "Sapphire Goods",
    state: "WA",
    quote_or_inquiry: "quote",
    status: "submitted-bound",
    assigned_underwriter: "Morgan Lee",
    needby_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    effective_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    last_updated: new Date().toISOString(),
    carrier: "Arden",
    agent: "Alex Carter",
    community: "Retail",
    stage: "Bound",
    opportunity_id: "OPP-2025-0007",
    detailed_stage: "Quote/Bind",
    client_email: "ops@sapphiregoods.example",
    client_phone: "(555) 201-1199",
    property: { address: "12 Aurora Rd, Seattle, WA", sq_ft: 26000, construction_type: "Masonry", year_built: 1995 },
    coverage_requested: ["Property"],
    missing_fields: [],
    carrier_options: [
      { name: "Arden", fit_score: 90, requirements: ["Acord 125"], reason: "Best premium/terms", selected: true },
    ],
    forms: [{ id: "f-125", name: "Acord 125", status: "completed", ai_confidence: 100 }],
    supporting_docs: [{ id: "d-sov", name: "SOV", uploaded: true }],
    submission: { status: "submitted" },
    quotes: [
      {
        carrier: "Arden",
        premium: 9800,
        deductible: 1000,
        effective_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
        selected: true,
      },
    ],
    policy: undefined,
  },
  {
    id: "c8",
    client_name: "Golden Ridge Farms",
    state: "IA",
    quote_or_inquiry: "quote",
    status: "submitted",
    assigned_underwriter: "Jamie Park",
    needby_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    effective_date: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000).toISOString(),
    last_updated: new Date().toISOString(),
    carrier: "Acme Insurance",
    agent: "Priya N.",
    community: "Construction",
    stage: "Policy Issued",
    opportunity_id: "OPP-2025-0008",
    detailed_stage: "Policy Issued",
    client_email: "ops@goldenridge.example",
    client_phone: "(555) 201-1200",
    property: { address: "88 Ridge Rd, Ames, IA", sq_ft: 40000, construction_type: "Wood Frame", year_built: 2005 },
    coverage_requested: ["General Liability", "Property"],
    missing_fields: [],
    carrier_options: [{ name: "Travelers", fit_score: 76, requirements: ["Acord 125"], reason: "Adequate fit" }],
    forms: [{ id: "f-125", name: "Acord 125", status: "completed", ai_confidence: 100 }],
    supporting_docs: [{ id: "d-photos", name: "Photos", uploaded: true }],
    submission: { status: "submitted" },
    quotes: [
      {
        carrier: "Travelers",
        premium: 13200,
        deductible: 1500,
        effective_date: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000).toISOString(),
        selected: true,
      },
    ],
    policy: { number: "PL-2025-0108", issued_at: new Date().toISOString() },
  },
]

export const recentlyViewedItems = [
  { id: "c3", client_name: "Cobalt Works", viewed_at: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  { id: "c1", client_name: "Blue Harbor LLC", viewed_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
]

export const activities = [
  {
    id: "a1",
    type: "new-lead",
    description: "Detected new lead from inbound email: Silver Pine Inc",
    created_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
  {
    id: "a2",
    type: "update",
    description: "Blue Harbor LLC uploaded Loss Runs",
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
]
